#!/usr/bin/env bash
#
# mock_claude.sh — Stub for claude CLI in tests
#
# Behavior controlled by env vars:
#   MOCK_CLAUDE_MODE        - "success" | "no_report" | "fail" | "hang"
#   MOCK_CLAUDE_PROMPT_DUMP - If set, dump the system prompt to this path
#
# Parses --append-system-prompt to extract the system prompt content.
# In "success" mode, extracts the output file path from the system prompt
# (looks for test-audit-*.md pattern).

MODE="${MOCK_CLAUDE_MODE:-success}"

# Parse args to find --append-system-prompt value
SYSTEM_PROMPT=""
USER_PROMPT=""
while [[ $# -gt 0 ]]; do
    case "$1" in
        --append-system-prompt)
            shift
            SYSTEM_PROMPT="$1"
            shift
            ;;
        --print|--dangerously-skip-permissions|--verbose)
            shift
            ;;
        --max-turns|--tools|--model|--system-prompt)
            shift; shift
            ;;
        -*)
            shift
            ;;
        *)
            USER_PROMPT="$1"
            shift
            ;;
    esac
done

# Optionally capture the system prompt for inspection
if [[ -n "${MOCK_CLAUDE_PROMPT_DUMP:-}" ]]; then
    echo "$SYSTEM_PROMPT" > "$MOCK_CLAUDE_PROMPT_DUMP"
fi

case "$MODE" in
    success)
        # Extract the output file path from the system prompt
        OUTPUT_FILE=$(echo "$SYSTEM_PROMPT" | grep -o '[^ ]*test-audit-[^ ]*\.md' | head -1)

        if [[ -z "$OUTPUT_FILE" ]]; then
            echo "mock_claude: could not extract output file path from system prompt" >&2
            exit 1
        fi

        mkdir -p "$(dirname "$OUTPUT_FILE")"
        cat > "$OUTPUT_FILE" <<'REPORT'
# Test Coverage Audit Report (MOCK)

**Module:** mock-module
**Generated by:** mock_claude

## Gap Report

No gaps found (this is a mock report for testing).

### Summary
- P0: 0 findings
- P1: 0 findings
- P2: 0 findings
REPORT
        exit 0
        ;;
    no_report)
        exit 0
        ;;
    fail)
        exit 1
        ;;
    hang)
        sleep 86400
        ;;
    *)
        echo "mock_claude: unknown mode '$MODE'" >&2
        exit 1
        ;;
esac
