#!/usr/bin/env bash
#
# mock_claude.sh — Stub for claude CLI in tests
#
# Behavior controlled by env vars:
#   MOCK_CLAUDE_MODE        - "success" | "no_report" | "fail" | "hang"
#   MOCK_CLAUDE_PROMPT_DUMP - If set, dump the received prompt to this path
#
# In "success" mode, extracts the output file path from the prompt by
# finding the line after "Write the COMPLETE gap report to this file:"
# that contains a file path (test-audit-*.md pattern).
#
# Modes:
#   "success"    - Create report at extracted path, exit 0
#   "no_report"  - Exit 0 but don't create the report
#   "fail"       - Exit 1
#   "hang"       - Sleep forever (for timeout testing)

MODE="${MOCK_CLAUDE_MODE:-success}"
PROMPT="${@: -1}"

# Optionally capture the prompt for inspection
if [[ -n "${MOCK_CLAUDE_PROMPT_DUMP:-}" ]]; then
    echo "$PROMPT" > "$MOCK_CLAUDE_PROMPT_DUMP"
fi

case "$MODE" in
    success)
        # Extract the output file path — it's the line containing "test-audit-"
        OUTPUT_FILE=$(echo "$PROMPT" | grep -o '[^ ]*test-audit-[^ ]*\.md' | head -1)

        if [[ -z "$OUTPUT_FILE" ]]; then
            echo "mock_claude: could not extract output file path from prompt" >&2
            exit 1
        fi

        mkdir -p "$(dirname "$OUTPUT_FILE")"
        cat > "$OUTPUT_FILE" <<'REPORT'
# Test Coverage Audit Report (MOCK)

**Module:** mock-module
**Generated by:** mock_claude

## Gap Report

No gaps found (this is a mock report for testing).

### Summary
- P0: 0 findings
- P1: 0 findings
- P2: 0 findings
REPORT
        exit 0
        ;;
    no_report)
        exit 0
        ;;
    fail)
        exit 1
        ;;
    hang)
        sleep 86400
        ;;
    *)
        echo "mock_claude: unknown mode '$MODE'" >&2
        exit 1
        ;;
esac
