#!/usr/bin/env python3
"""One-shot migration: seed SKILL.md front matter from legacy registries.

Reads keywords/file_patterns/confidence from the three legacy registry files
and merges them into each skill's own SKILL.md front matter.

Sources:
    skills/skill-rules.json          — name, keywords
    skills/activation.yaml           — name, keywords
    skills/recommendation-rules.json — name, file_patterns, confidence

Outputs:
    skills/<skill>/SKILL.md                                   — updated front matter
    skills/skill-index.json                                   — regenerated by cortex skills rebuild-index
    docs/devel/reports/skill-keywords-needing-review.md       — skills with empty keywords after merge
    docs/devel/reports/skill-migration-orphans.md             — registry refs with no matching dir

Idempotent: running twice produces no further diff.

After Phase 5 this script becomes unnecessary; it is kept in the repo for
auditability of the migration.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path
from typing import Any, Dict, List, Optional, Set, Tuple

import yaml

REPO_ROOT = Path(__file__).resolve().parent.parent
SKILLS_ROOT = REPO_ROOT / "skills"
REPORTS_DIR = REPO_ROOT / "docs" / "devel" / "reports"

# Skills that were renamed since the legacy registries were last authored.
# Maps legacy name -> current name.
RENAMES: Dict[str, str] = {
    "ctx-brainstorming": "brainstorming",
    "ctx-plan-writing": "writing-plans",
    "ctx-plan-execution": "executing-plans",
}

# Keep front matter emission in a predictable order so diffs stay small.
KEY_ORDER: Tuple[str, ...] = (
    "name",
    "description",
    "keywords",
    "file_patterns",
    "confidence",
)


class SkillAggregate:
    """Mutable bucket accumulating legacy-registry data for one skill name."""

    __slots__ = ("keywords", "file_patterns", "confidence", "sources")

    def __init__(self) -> None:
        self.keywords: Set[str] = set()
        self.file_patterns: Set[str] = set()
        self.confidence: Optional[float] = None
        self.sources: Set[str] = set()

    def add_confidence(self, value: Optional[float]) -> None:
        if value is None:
            return
        if self.confidence is None or value > self.confidence:
            self.confidence = value


def load_aggregates(skills_root: Path) -> Dict[str, SkillAggregate]:
    """Merge all three registries into a single name -> aggregate map."""
    aggregates: Dict[str, SkillAggregate] = {}

    # skill-rules.json: rules[].{name, keywords}
    rules_path = skills_root / "skill-rules.json"
    if rules_path.exists():
        data = json.loads(rules_path.read_text(encoding="utf-8"))
        for rule in data.get("rules", []):
            name = RENAMES.get(rule.get("name", ""), rule.get("name", ""))
            if not name:
                continue
            agg = aggregates.setdefault(name, SkillAggregate())
            agg.sources.add("skill-rules.json")
            for kw in rule.get("keywords", []) or []:
                if isinstance(kw, str) and kw.strip():
                    agg.keywords.add(kw.strip())

    # activation.yaml: skills.<name>.keywords
    activation_path = skills_root / "activation.yaml"
    if activation_path.exists():
        data = yaml.safe_load(activation_path.read_text(encoding="utf-8")) or {}
        for raw_name, cfg in (data.get("skills") or {}).items():
            name = RENAMES.get(raw_name, raw_name)
            agg = aggregates.setdefault(name, SkillAggregate())
            agg.sources.add("activation.yaml")
            if isinstance(cfg, dict):
                for kw in cfg.get("keywords", []) or []:
                    if isinstance(kw, str) and kw.strip():
                        agg.keywords.add(kw.strip())

    # recommendation-rules.json: rules[].trigger.file_patterns + rules[].recommend[].{skill, confidence}
    rec_path = skills_root / "recommendation-rules.json"
    if rec_path.exists():
        data = json.loads(rec_path.read_text(encoding="utf-8"))
        for rule in data.get("rules", []):
            file_patterns = (
                rule.get("trigger", {}).get("file_patterns", []) or []
            )
            for rec in rule.get("recommend", []) or []:
                name = RENAMES.get(rec.get("skill", ""), rec.get("skill", ""))
                if not name:
                    continue
                agg = aggregates.setdefault(name, SkillAggregate())
                agg.sources.add("recommendation-rules.json")
                for fp in file_patterns:
                    if isinstance(fp, str) and fp.strip():
                        agg.file_patterns.add(fp.strip())
                confidence = rec.get("confidence")
                if isinstance(confidence, (int, float)) and not isinstance(
                    confidence, bool
                ):
                    agg.add_confidence(float(confidence))

    return aggregates


def index_skills_on_disk(skills_root: Path) -> Dict[str, Path]:
    """Walk skills_root and return {name_in_front_matter: path-to-SKILL.md}."""
    result: Dict[str, Path] = {}
    for skill_md in skills_root.rglob("SKILL.md"):
        rel = skill_md.relative_to(skills_root)
        if any(part.startswith(".") for part in rel.parts[:-1]):
            continue
        front_matter = _extract_front_matter(
            skill_md.read_text(encoding="utf-8", errors="replace")
        )
        if front_matter is None:
            continue
        data = yaml.safe_load(front_matter) or {}
        if not isinstance(data, dict):
            continue
        name = data.get("name")
        if isinstance(name, str) and name.strip():
            result[name.strip()] = skill_md
    return result


def merge_into_skill_md(
    skill_md: Path,
    add_keywords: Set[str],
    add_file_patterns: Set[str],
    add_confidence: Optional[float],
) -> bool:
    """Merge aggregate data into skill_md's front matter. Returns True on write."""
    original = skill_md.read_text(encoding="utf-8")
    raw_front_matter = _extract_front_matter(original)
    if raw_front_matter is None:
        return False

    data = yaml.safe_load(raw_front_matter) or {}
    if not isinstance(data, dict):
        return False

    existing_kw: Set[str] = set()
    if isinstance(data.get("keywords"), list):
        existing_kw.update(
            k.strip() for k in data["keywords"] if isinstance(k, str) and k.strip()
        )
    # `triggers:` is accepted as a legacy alias; absorb and drop.
    if isinstance(data.get("triggers"), list):
        existing_kw.update(
            t.strip() for t in data["triggers"] if isinstance(t, str) and t.strip()
        )
        data.pop("triggers", None)
    merged_kw = existing_kw | add_keywords

    existing_fp: Set[str] = set()
    if isinstance(data.get("file_patterns"), list):
        existing_fp.update(
            p.strip() for p in data["file_patterns"] if isinstance(p, str) and p.strip()
        )
    merged_fp = existing_fp | add_file_patterns

    existing_conf = data.get("confidence")
    merged_conf: Optional[float]
    if isinstance(existing_conf, (int, float)) and not isinstance(existing_conf, bool):
        merged_conf = float(existing_conf)
    else:
        merged_conf = None
    if add_confidence is not None:
        if merged_conf is None or add_confidence > merged_conf:
            merged_conf = add_confidence

    if merged_kw:
        data["keywords"] = sorted(merged_kw)
    elif "keywords" in data:
        # Preserve the empty list rather than deleting — signals "has front matter, no keywords yet"
        data["keywords"] = []

    if merged_fp:
        data["file_patterns"] = sorted(merged_fp)
    elif "file_patterns" in data:
        data.pop("file_patterns", None)

    if merged_conf is not None:
        data["confidence"] = merged_conf

    new_front_matter = _format_front_matter(data)
    new_text = _replace_front_matter(original, new_front_matter)
    if new_text == original:
        return False
    skill_md.write_text(new_text, encoding="utf-8")
    return True


def _extract_front_matter(text: str) -> Optional[str]:
    stripped = text.lstrip()
    if not stripped.startswith("---"):
        return None
    parts = stripped.split("---", 2)
    if len(parts) < 3:
        return None
    return parts[1]


def _replace_front_matter(original: str, new_front_matter: str) -> str:
    """Swap the first ``---``-delimited block in ``original`` for new content."""
    leading_len = len(original) - len(original.lstrip())
    leading = original[:leading_len]
    body_after_leading = original[leading_len:]
    after_first = body_after_leading[3:]  # drop opening '---'
    parts = after_first.split("---", 1)
    if len(parts) < 2:
        return original
    trailing_body = parts[1]
    # Preserve leading newline on body after the closing '---'
    return f"{leading}---\n{new_front_matter}---{trailing_body}"


class _IndentedDumper(yaml.SafeDumper):
    """SafeDumper that indents block-style list items under their parent key."""

    def increase_indent(
        self, flow: bool = False, indentless: bool = False
    ) -> None:
        super().increase_indent(flow, False)


def _format_front_matter(data: Dict[str, Any]) -> str:
    """Serialise ``data`` to YAML with our canonical key order."""
    ordered: Dict[str, Any] = {}
    for key in KEY_ORDER:
        if key in data:
            ordered[key] = data[key]
    for key, value in data.items():
        if key not in ordered:
            ordered[key] = value

    return yaml.dump(
        ordered,
        Dumper=_IndentedDumper,
        sort_keys=False,
        allow_unicode=True,
        default_flow_style=False,
        width=10_000,
    )


def write_reports(
    aggregates: Dict[str, SkillAggregate],
    on_disk: Dict[str, Path],
    skills_root: Path,
    reports_dir: Path,
) -> Tuple[int, int]:
    """Emit gap and orphan reports. Returns ``(gap_count, orphan_count)``."""
    reports_dir.mkdir(parents=True, exist_ok=True)

    # Gap: skills on disk with no keywords after migration.
    gaps: List[Tuple[str, Path]] = []
    for name, skill_md in sorted(on_disk.items()):
        front_matter = _extract_front_matter(
            skill_md.read_text(encoding="utf-8", errors="replace")
        )
        data = yaml.safe_load(front_matter or "") or {}
        kw = data.get("keywords") if isinstance(data, dict) else None
        if not (isinstance(kw, list) and any(isinstance(k, str) and k.strip() for k in kw)):
            gaps.append((name, skill_md))

    gap_report = reports_dir / "skill-keywords-needing-review.md"
    gap_lines: List[str] = [
        "# Skills Needing Keyword Review",
        "",
        "Skills whose `SKILL.md` front matter has no keywords after the legacy-registry migration.",
        "",
        "These skills will appear in `skill-index.json` but will not match any prompt or file-path search until keywords are added.",
        "",
        f"Total: {len(gaps)} skills.",
        "",
    ]
    for name, skill_md in gaps:
        rel = skill_md.relative_to(skills_root).as_posix()
        gap_lines.append(f"- [ ] `{name}` — `skills/{rel}`")
    gap_lines.append("")
    gap_report.write_text("\n".join(gap_lines), encoding="utf-8")

    # Orphans: registry-only names that do not match any directory on disk.
    orphans = sorted(
        name for name in aggregates if name not in on_disk
    )
    orphan_report = reports_dir / "skill-migration-orphans.md"
    orphan_lines: List[str] = [
        "# Skill Migration Orphans",
        "",
        "Skill names referenced by the legacy registries that have no matching directory on disk.",
        "",
        "These were skipped during migration and should be audited before Phase 5 deletes the legacy files.",
        "",
        f"Total: {len(orphans)} orphans.",
        "",
    ]
    for name in orphans:
        agg = aggregates[name]
        sources = ", ".join(sorted(agg.sources))
        orphan_lines.append(f"- `{name}` — referenced by: {sources}")
    orphan_lines.append("")
    orphan_report.write_text("\n".join(orphan_lines), encoding="utf-8")

    return len(gaps), len(orphans)


def main() -> int:
    if not SKILLS_ROOT.is_dir():
        print(f"error: skills root not found: {SKILLS_ROOT}", file=sys.stderr)
        return 1

    aggregates = load_aggregates(SKILLS_ROOT)
    on_disk = index_skills_on_disk(SKILLS_ROOT)

    written = 0
    for name, agg in aggregates.items():
        skill_md = on_disk.get(name)
        if skill_md is None:
            continue
        if merge_into_skill_md(
            skill_md,
            add_keywords=agg.keywords,
            add_file_patterns=agg.file_patterns,
            add_confidence=agg.confidence,
        ):
            written += 1

    gap_count, orphan_count = write_reports(
        aggregates, on_disk, SKILLS_ROOT, REPORTS_DIR
    )

    print(
        f"migrated {written} SKILL.md files; "
        f"{gap_count} skills need keyword review; "
        f"{orphan_count} registry refs orphaned."
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
